name: docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 805601245952.dkr.ecr.eu-central-1.amazonaws.com/my-flask-app
          username: AWS
          password: ${{ secrets.ECR_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 805601245952.dkr.ecr.eu-central-1.amazonaws.com/my-flask-app:latest
